catalog:
  tag: "ffe1df"
orders_db:
  tag: "6996a8"
catalog_db:
  tag: "ffe1df"
cart:
  tag: "69e73f"
cart_dynamodb:
  tag: "69e73f"
orders:
  tag: "6996a8"
assets_rabbitmq:
  tag: "6996a8"
checkout:
  tag: "b45290"
checkout_db:
  tag: "b45290"
assets:
  tag: "4c2902"
ui:
  tag: "b390b1"
